// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"jzlservice/smssender"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  list<SMSStatus> sendSMS(1: list<SMSEntry> sms_entries)")
	fmt.Fprintln(os.Stderr, "  SMSStatus sendMessage(1: SMSEntry sms_entry)")
	fmt.Fprintln(os.Stderr, "  SMSBalance getBalance()")
	fmt.Fprintln(os.Stderr, "  SMSReport getReport()")
	fmt.Fprintln(os.Stderr, "  SMSMOMessage getMOMessage()")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = math.MinInt32 // will become unneeded eventually
	_ = strconv.Atoi
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := smssender.NewSMSSenderClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "ping":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "Ping requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.Ping())
		fmt.Print("\n")
		break
	case "getBalance":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetBalance requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetBalance())
		fmt.Print("\n")
		break
	case "getReport":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetReport requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetReport())
		fmt.Print("\n")
		break
	case "getMOMessage":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetMOMessage requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetMOMessage())
		fmt.Print("\n")
		break
	case "sendSMS":
		/*
			if flag.NArg()-1 != 1 {
				fmt.Fprintln(os.Stderr, "SendSMS requires 1 args")
				flag.Usage()
			}
			arg15 := flag.Arg(1)
			mbTrans16 := thrift.NewTMemoryBufferLen(len(arg15))
			defer mbTrans16.Close()
			_, err17 := mbTrans16.WriteString(arg15)
			if err17 != nil {
				Usage()
				return
			}
			factory18 := thrift.NewTSimpleJSONProtocolFactory()
			jsProt19 := factory18.GetProtocol(mbTrans16)
			containerStruct0 := smssender.NewSendSMSArgs()
			err20 := containerStruct0.Read(jsProt19)
			if err20 != nil {
				Usage()
				return
			}
			argvalue0 := containerStruct0.SmsEntries
			value0 := argvalue0
		*/

		entryies := []*smssender.SMSEntry{
			&smssender.SMSEntry{1, "1", "这是一个测试消息。", "13401173761", "枝兰", "", 1},
			&smssender.SMSEntry{2, "2", "齐芃送给您一个50元春播红包，用它可选购春播全场食品，无运费，享用完记得感谢齐芃哦！点击链接且用手机号注册以后即可领取http://t.cn/R2mxRPa", "13401173761", "春播", "", 1},
		}

		fmt.Print(client.SendSMS(entryies))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
